<?php if($tab==='customers'):
$customers=db()->query("SELECT u.id,u.name,u.email,u.phone,u.created_at,COUNT(o.id) orders_count,COALESCE(SUM(CASE WHEN o.order_status<>'cancelled' THEN o.total ELSE 0 END),0) spent FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.id DESC")->fetchAll();
?>
<section class="admin-panel"><h2>Customers</h2><p class="admin-section-intro">Registered customer accounts and their order activity.</p><?php if(!$customers): ?><p class="dash-empty">No customer accounts yet.</p><?php else: ?><div class="dash-table-scroll"><table class="dash-table"><thead><tr><th>Customer</th><th>Email</th><th>Phone</th><th>Orders</th><th>Order value</th><th>Joined</th><th>History</th></tr></thead><tbody><?php foreach($customers as $row): ?><tr><td><strong><?=e($row['name'])?></strong></td><td><?=e($row['email'])?></td><td><?=e($row['phone']?:'—')?></td><td><?=e($row['orders_count'])?></td><td><?=price($row['spent'])?></td><td><?=e(date('M j, Y',strtotime($row['created_at'])))?></td><td><a href="<?=path('admin',['tab'=>'orders','customer_id'=>$row['id']])?>">View orders →</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php elseif($tab==='inventory'): include __DIR__.'/admin-inventory.php'; ?>
<?php elseif($tab==='payments'):
$payments=db()->query('SELECT p.id,o.order_no,o.customer_name,p.payment_method,p.amount,p.status,p.created_at FROM payments p JOIN orders o ON o.id=p.order_id ORDER BY p.id DESC')->fetchAll();
?>
<section class="admin-panel"><h2>Payments</h2><p class="admin-section-intro">Payment records created at checkout. Digital payments still need manual confirmation.</p><?php if(!$payments): ?><p class="dash-empty">No payment records yet.</p><?php else: ?><div class="dash-table-scroll"><table class="dash-table"><thead><tr><th>Order</th><th>Customer</th><th>Method</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody><?php foreach($payments as $row): ?><tr><td><?=e($row['order_no'])?></td><td><?=e($row['customer_name'])?></td><td><?=e(strtoupper($row['payment_method']))?></td><td><?=price($row['amount'])?></td><td><span class="badge"><?=e($row['status'])?></span></td><td><?=e(date('M j, Y',strtotime($row['created_at'])))?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php endif; ?>
