<?php if($tab==='customers'):
$customers=db()->query("SELECT u.id,u.name,u.email,u.phone,u.created_at,COUNT(o.id) orders_count,COALESCE(SUM(CASE WHEN o.order_status<>'cancelled' THEN o.total ELSE 0 END),0) spent FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.id DESC")->fetchAll();
?>
<section class="admin-panel"><h2>Customers</h2><p class="admin-section-intro">Registered customer accounts and their order activity.</p><?php if(!$customers): ?><p class="dash-empty">No customer accounts yet.</p><?php else: ?><div class="dash-table-scroll"><table class="dash-table"><thead><tr><th>Customer</th><th>Email</th><th>Phone</th><th>Orders</th><th>Order value</th><th>Joined</th></tr></thead><tbody><?php foreach($customers as $row): ?><tr><td><strong><?=e($row['name'])?></strong></td><td><?=e($row['email'])?></td><td><?=e($row['phone']?:'—')?></td><td><?=e($row['orders_count'])?></td><td><?=price($row['spent'])?></td><td><?=e(date('M j, Y',strtotime($row['created_at'])))?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php elseif($tab==='inventory'):
$variants=db()->query('SELECT p.id product_id,p.name,p.image,v.size,v.sku,v.stock,v.status FROM product_variants v JOIN products p ON p.id=v.product_id ORDER BY v.stock ASC,p.name,v.size')->fetchAll();
?>
<section class="admin-panel"><h2>Inventory</h2><p class="admin-section-intro">Update sizes and stock from each product’s edit page.</p><?php if(!$variants): ?><p class="dash-empty">No inventory records yet.</p><?php else: ?><div class="dash-table-scroll"><table class="dash-table"><thead><tr><th>Product</th><th>Size</th><th>SKU</th><th>Stock</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($variants as $row): ?><tr><td><strong><?=e($row['name'])?></strong></td><td><?=e($row['size'])?></td><td><?=e($row['sku'])?></td><td class="<?=$row['stock']<=5?'dash-stock-count':''?>"><?=e($row['stock'])?></td><td><?=e($row['status']?'Active':'Hidden')?></td><td><a href="<?=path('admin',['tab'=>'products','edit'=>$row['product_id']])?>">Edit →</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php elseif($tab==='payments'):
$payments=db()->query('SELECT p.id,o.order_no,o.customer_name,p.payment_method,p.amount,p.status,p.created_at FROM payments p JOIN orders o ON o.id=p.order_id ORDER BY p.id DESC')->fetchAll();
?>
<section class="admin-panel"><h2>Payments</h2><p class="admin-section-intro">Payment records created at checkout. Digital payments still need manual confirmation.</p><?php if(!$payments): ?><p class="dash-empty">No payment records yet.</p><?php else: ?><div class="dash-table-scroll"><table class="dash-table"><thead><tr><th>Order</th><th>Customer</th><th>Method</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody><?php foreach($payments as $row): ?><tr><td><?=e($row['order_no'])?></td><td><?=e($row['customer_name'])?></td><td><?=e(strtoupper($row['payment_method']))?></td><td><?=price($row['amount'])?></td><td><span class="badge"><?=e($row['status'])?></span></td><td><?=e(date('M j, Y',strtotime($row['created_at'])))?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php endif; ?>
